Improving kerasfunc2json.py compatibility
lwtnn/lwtnn pull request #158
Opened 2021-11-25 08:30 UTC by sfranchel

Making `converters/kerasfunc2json.py` compatible with dropout layers in  `timedistributed` type of layers.

2021-11-25 08:59 UTC, dguest requested changes
Looks pretty reasonable overall. We could consolidate your logic a bit. Let's see what the CI tells us.

2021-11-25 08:59 UTC, dguest commented on converters/kerasfunc2json.py
> +    """Top level routine"""
We don't want to add trailing whitespace, I think @matthewfeickert's linting magic will pick up on this though

2021-11-25 08:59 UTC, dguest commented on converters/kerasfunc2json.py
> +        node.sources = source_nodes
your indentation looks right, I'm just surprised the linter allowed what we had before

2021-11-25 08:59 UTC, dguest commented on converters/kerasfunc2json.py
> +            removed_nodes.add(node_index)
I think here, and in the line below, we want some function like `_is_a_skipped_node(node): ... ` that executes the logic in this strong

2021-11-25 08:59 UTC, dguest commented on converters/kerasfunc2json.py
>      else:
Related comment to the one above here: we really want something like

```python
if not _is_a_skipped_node(node):
    return node_source
else:
    ....
```
to avoid repeating the same logic (in slightly different ways) in two places

2021-11-25 09:54 UTC, dguest commented
Yeah the linter picked up the trailing whitespace, as I expected. Good news is that everything else seemed to work fine.

2021-11-25 11:36 UTC, sfranchel commented on converters/kerasfunc2json.py
> +    """Top level routine"""
ops, that one was a mistake...

2021-11-25 11:37 UTC, sfranchel commented on converters/kerasfunc2json.py
>      else:
Ok, I can put all that in a single function

2021-11-29 08:39 UTC, dguest commented
Hi @sfranchel I think we're still failing linting tests because of trailing white space. You can usually set your text editor to highlight this.

2021-11-29 08:44 UTC, matthewfeickert commented on converters/kerasfunc2json.py
> +        node.sources = source_nodes
I didn't setup enforcement of tabs vs. spaces in the linter in PR #133. Though we can. :)

2021-11-29 08:47 UTC, matthewfeickert commented
> I think we're still failing linting tests because of trailing white space. You can usually set your text editor to highlight this.

@sfranchel to make this easy on you, my recommendation is (assuming you already have a Python virtual environment setup for running the tests) in your virtual environment just install `pre-commit` and then run it from the top level of the repo to pick up the pre-commit config:

```console
$ python -m pip install pre-commit
$ pre-commit run --all-files
```

2021-11-29 09:58 UTC, dguest commented on converters/kerasfunc2json.py
> +        node.sources = source_nodes
Oh god, so we might have tabs all over the place... I don't really want to make yet another commit that touches hundreds of lines just for this. Is there some way we can make the linter only complain about changed lines that contain tabs?

2021-11-29 14:09 UTC, merged

2021-11-29 14:09 UTC, dguest commented
Merged, thanks @sfranchel!

2021-11-29 22:19 UTC, matthewfeickert commented on converters/kerasfunc2json.py
> +        node.sources = source_nodes
For posterity, PR #159 showed us that we only had to touch 1 line. Small miracles happen. :)